name: CS Check

on: [push, pull_request]

jobs:
  cs-check:
    name: Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-ubuntu-${{ github.sha }}

      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, fileinfo, json, intl, dom
          tools: castor

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Install qa tooling
        run: castor qa:update

      - name: Check coding standards
        run: castor qa:cs --dry-run
